import { ListingInput } from './types';

export const sampleInventory: ListingInput[] = [
  {
    title: 'Patagonia Better Sweater Full-Zip Jacket Heather Gray Women',
    brand: 'Patagonia',
    category: 'Fashion Apparel',
    condition: 'Good used condition',
    size: 'M',
    color: 'Gray',
    material: 'Polyester fleece',
    purchaseCost: 18,
    targetSalePrice: 55,
    shippingPaid: 7.9,
    shippingCharged: 7.9,
    platform: 'eBay',
    listingAgeDays: 22,
    notes: 'Minor pilling on cuffs',
    safetyDocs: false,
    gradingDescriptors: false,
  },
  {
    title: 'Vintage Levi Denim Jacket',
    brand: 'Levi\'s',
    category: 'Fashion Apparel',
    condition: '',
    size: 'Large',
    color: 'Blue',
    material: 'Cotton',
    purchaseCost: 22,
    targetSalePrice: 48,
    shippingPaid: 8.5,
    shippingCharged: 7.5,
    platform: 'Facebook Marketplace',
    listingAgeDays: 84,
    notes: '',
    safetyDocs: false,
    gradingDescriptors: false,
  },
  {
    title: 'Certified Silver Eagle Coin 2004 MS69',
    brand: '',
    category: 'Coin Collectible',
    condition: 'Excellent',
    size: '',
    color: 'Silver',
    material: 'Silver',
    purchaseCost: 24,
    targetSalePrice: 45,
    shippingPaid: 4.2,
    shippingCharged: 5,
    platform: 'Poshmark',
    listingAgeDays: 102,
    notes: 'Slabbed',
    safetyDocs: false,
    gradingDescriptors: false,
  },
];
