import { ListingInput } from './types';

export const sampleInventory: ListingInput[] = [
  {
    title: 'Coach Legacy Leather Tote Bag Brown Turnlock Shoulder Purse',
    brand: 'Coach',
    category: 'Fashion Accessories',
    condition: 'Good pre-owned condition with light corner wear',
    size: 'One Size',
    color: 'Brown',
    material: 'Leather',
    purchaseCost: 22,
    targetSalePrice: 92,
    shippingPaid: 9.25,
    shippingCharged: 8.95,
    platform: 'eBay',
    listingAgeDays: 86,
    notes: 'Good brand and margin, but stale listing needs stronger title/photos.',
    safetyDocs: false,
    gradingDescriptors: false,
  },
  {
    title: 'Vintage Louis Marx Animal Kingdom Toy Figures With Original Boxes',
    brand: 'Louis Marx',
    category: 'Vintage Toy Collectible',
    condition: 'Used vintage condition with box wear and mixed figures',
    size: 'OS',
    color: 'Multi',
    material: 'Plastic and cardboard',
    purchaseCost: 35,
    targetSalePrice: 140,
    shippingPaid: 14,
    shippingCharged: 12,
    platform: 'Facebook Marketplace',
    listingAgeDays: 18,
    notes: 'Collectible with good upside. Better buyer pool likely on eBay.',
    safetyDocs: false,
    gradingDescriptors: false,
  },
  {
    title: 'Nike Air Max Womens Sneakers Size 8 White Pink',
    brand: 'Nike',
    category: 'Shoes Fashion',
    condition: 'Pre-owned with visible sole wear',
    size: '8',
    color: 'White Pink',
    material: 'Synthetic mesh rubber',
    purchaseCost: 28,
    targetSalePrice: 58,
    shippingPaid: 10,
    shippingCharged: 7.97,
    platform: 'Poshmark',
    listingAgeDays: 74,
    notes: 'Shipping and wear reduce profit. Needs price correction.',
    safetyDocs: false,
    gradingDescriptors: false,
  },
  {
    title: 'Lancome Skincare Minis Gift With Purchase Bundle',
    brand: 'Lancome',
    category: 'Beauty Skincare Bundle',
    condition: 'New unused minis from gift set',
    size: 'OS',
    color: 'Multi',
    material: 'Cosmetic skincare',
    purchaseCost: 6,
    targetSalePrice: 26,
    shippingPaid: 5.25,
    shippingCharged: 4.95,
    platform: 'eBay',
    listingAgeDays: 49,
    notes: 'Low-ticket item. Best recovered through bundle strategy.',
    safetyDocs: false,
    gradingDescriptors: false,
  },
  {
    title: '2004 American Silver Eagle Coin MS69 Certified Slab',
    brand: 'US Mint',
    category: 'Coin Collectible',
    condition: 'Certified MS69 slabbed coin',
    size: 'OS',
    color: 'Silver',
    material: 'Silver',
    purchaseCost: 31,
    targetSalePrice: 55,
    shippingPaid: 4.75,
    shippingCharged: 5.25,
    platform: 'Poshmark',
    listingAgeDays: 109,
    notes: 'Wrong platform and grading details must be explicit.',
    safetyDocs: false,
    gradingDescriptors: true,
  },
  {
    title: 'Kids Imported Light Up Toy Wand Party Favor',
    brand: '',
    category: 'Children Import Regulated Toy',
    condition: 'New without retail packaging',
    size: 'OS',
    color: 'Pink',
    material: 'Plastic electronic components',
    purchaseCost: 4,
    targetSalePrice: 12,
    shippingPaid: 4.5,
    shippingCharged: 3.95,
    platform: 'Facebook Marketplace',
    listingAgeDays: 93,
    notes: 'Weak margin and regulated category risk. Safety documentation missing.',
    safetyDocs: false,
    gradingDescriptors: false,
  },
  {
    title: 'Solid Wood Coffee Table Local Pickup Rustic Farmhouse',
    brand: 'Unbranded',
    category: 'Furniture Local Pickup',
    condition: 'Used with surface scratches',
    size: 'OS',
    color: 'Brown',
    material: 'Wood',
    purchaseCost: 18,
    targetSalePrice: 95,
    shippingPaid: 0,
    shippingCharged: 0,
    platform: 'eBay',
    listingAgeDays: 41,
    notes: 'Bulky item should be local-first, not eBay-first.',
    safetyDocs: false,
    gradingDescriptors: false,
  },
  {
    title: 'Shein Floral Blouse',
    brand: 'Shein',
    category: 'Fashion Apparel',
    condition: 'Good used condition',
    size: 'Medium',
    color: 'Floral',
    material: 'Polyester',
    purchaseCost: 5,
    targetSalePrice: 14,
    shippingPaid: 4.95,
    shippingCharged: 3.95,
    platform: 'eBay',
    listingAgeDays: 132,
    notes: 'Low-ticket stale item with weak resale upside.',
    safetyDocs: false,
    gradingDescriptors: false,
  },
  {
    title: 'Burberry Nova Check Wallet Beige Leather Canvas Authentic',
    brand: 'Burberry',
    category: 'Designer Fashion Accessories',
    condition: 'Pre-owned with edge wear and interior marks',
    size: 'One Size',
    color: 'Beige',
    material: 'Canvas leather',
    purchaseCost: 40,
    targetSalePrice: 135,
    shippingPaid: 6.5,
    shippingCharged: 6.95,
    platform: 'eBay',
    listingAgeDays: 27,
    notes: 'Good hold candidate if authenticity and condition photos are strong.',
    safetyDocs: false,
    gradingDescriptors: false,
  },
  {
    title: 'Mixed Costume Jewelry Lot Wear Repair Craft Resale',
    brand: 'Mixed',
    category: 'Jewelry Accessories Lot',
    condition: 'Mixed used condition with wear and repair pieces',
    size: 'OS',
    color: 'Gold Silver Multi',
    material: 'Mixed metal',
    purchaseCost: 9,
    targetSalePrice: 32,
    shippingPaid: 6.2,
    shippingCharged: 5.95,
    platform: 'Mercari',
    listingAgeDays: 67,
    notes: 'Better sold as bundle/lot with clear condition disclosure.',
    safetyDocs: false,
    gradingDescriptors: false,
  },
];
